spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    name: training_location
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
api:
  security:
    token:
      secret: ${TOKENSECRET}
