spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/training
    username: postgres
    password: 030401260180
    name: training_location
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
api:
  security:
    token:
      secret: banana
